Blog/Models/BlogDatabaseSettings.cs
namespace Blog.Models
{
    public class BlogDatabaseSettings : IBlogDatabaseSettings
    {
        public string BlogCollectionName { get; set; }
        public string ConnectionString { get; set; }
        public string DatabaseName { get; set; }
    }

    public interface IBlogDatabaseSettings
    {
        string BlogCollectionName { get; set; }
        string ConnectionString { get; set; }
        string DatabaseName { get; set; }
    }
}

Blog/Models/Post.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Blog.Models
{
    [BsonIgnoreExtraElements]
    public class Post
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }
        
        public string Title { get; set; }
        
        public string Author { get; set; }
        
        public string Body { get; set; }
    }
}

Blog/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class AdminController : Controller
    {
        public ViewResult Login()
        {
            return View();
        }

        public ViewResult Registration()
        {
            return View();
        }
    }
}

Blog/Controllers/LoginController.cs
namespace Blog.Controllers
{
    public class LoginController
    {
        
    }
}

Blog/Controllers/PostController.cs
using System.Collections.Generic;
using Blog.Models;
using Blog.Services;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class PostController : Controller
    {
        private readonly PostService _postService;

        public PostController(PostService postService)
        {
            _postService = postService;
        }

        public ViewResult Post()
        {
            var posts = _postService.Get();
            return View(model: posts);
        }
        
    }
}

Blog/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class RegistrationController : Controller
    {
        public RedirectResult Registration()
        {
            return Redirect("~/Admin/Login");
        }
    }
}

Blog/Views/Admin/Login.cshtml
@{
    Layout = "_AdminLayout";
}

<h1>Login form</h1>
<form asp-controller="Login" asp-action="Login" method="post">
    <div class="form-group">
        <label for="username">Username</label>
        <input class="form-control" type="text" id="username" name="username"/>
    </div>
    
    <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" type="password" id="password" name="password"/>
    </div>
    
    <div class="form-group">
        <input class="btn btn-primary" type="submit" name="submit" value="Login"/>
    </div>
</form>

Blog/Views/Admin/Registration.cshtml
@{
    Layout = "_AdminLayout";
}


<h1>Registration form</h1>
<form asp-controller="Registration" asp-action="Registration" method="post">
    <div class="form-group">
        <label for="username">Username</label>
        <input class="form-control" type="text" id="username" name="username"/>
    </div>
    
    <div class="form-group">
        <label for="bio">BIO</label>
        <input class="form-control" type="text" id="bio" name="bio" maxlength="80"/>
    </div>
    
    <div class="form-group">
        <label for="email">Email</label>
        <input class="form-control" type="email" id="email" name="email"/>
    </div>
    
    <div class="form-group">
        <label for="password1">Password</label>
        <input class="form-control" type="password" id="password1" name="password1"/>
    </div>
    
    <div class="form-group">
        <label for="password2">Confirm password</label>
        <input class="form-control" type="password" id="password2" name="password2"/>
    </div>
    
    <div class="form-group">
       <input class="btn btn-primary" type="submit" name="submit" value="Login"/>
    </div>
</form>

Blog/Views/Post/Post.cshtml
@model List<Post>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

@{
    foreach (var post in Model)
    {
        <div>
            <p>@post.Body.Substring(0, 80)</p>
            <h5>@post.Author</h5>
            <hr/>
        </div>
    }
}

Blog/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Post" asp-action="Post">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Post">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Post">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Blog - <a asp-area="" asp-controller="Post" asp-action="Post">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Post" asp-action="Post">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Post">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Post">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Blog - <a asp-area="" asp-controller="Post" asp-action="Post">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>